Update HouseRegion.cs
TrueUO/TrueUO pull request #505
Opened 2020-11-05 21:13 UTC by Argalep

Fixed the issue where items found on the stairs were displayed.

2020-11-05 23:27 UTC, kevin-10 requested changes
You can't do this. This will adversely effect addon placement.

2020-11-05 23:46 UTC, Argalep commented
> You can't do this. This will adversely effect addon placement.

this function only affects the ability to see items. Also, there is a problem with the items on the stairs now. When another chest is placed on the chest on the stairs, players cannot open it.

![79B574D9-9BE6-4373-AE27-102C4FFA8B24](https://user-images.githubusercontent.com/17765272/98308928-4ff94580-1fda-11eb-80cf-e05d4d4eb61d.png)

2020-11-06 02:14 UTC, kevin-10 commented
Put htis in HouseFoundation instead:

 public override bool IsStairArea(IPoint3D p, out bool frontStairs)
        {
            if (p.Y >= Sign.Y)
            {
                frontStairs = true;
                return true;
            }

            frontStairs = false;
            return false;
        }

2020-11-06 19:12 UTC, kevin-10 approved these changes

2020-11-06 19:27 UTC, merged